export { default as About } from './about'
export { default as Blog } from './blog'
export { default as Contact } from './contact'
export { default as Hero } from './hero'
export { default as Projects } from './projects'
